class MappingInvalidError(Exception): ...  

class MappingInvalidHintError(Exception): ...

class MappingNotFoundError(Exception): ...

class MappingTaskNotFoundError(Exception): ... 

class CircularReferenceError(Exception): ... 

